
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aleix
 */
public class FacturesClientDetalls extends javax.swing.JFrame {

    /**
     * Creates new form ClientInsert
     */
    Connection con;
    public static Statement stmt = null;
    public static ResultSet rs = null;
    String DNI;
    DefaultTableModel tableModel = new DefaultTableModel();

    public FacturesClientDetalls(Connection c, String DNI, int num_factura) {
        con = c;
        this.DNI = DNI;
        initComponents();
        this.setLocationRelativeTo(null);
        jTableQueryResult.setCellSelectionEnabled(false);
        jTableQueryResult.setFocusable(false);
        getDadesFactura(num_factura);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGoBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableQueryResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalls factura");

        jButtonGoBack.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonGoBack.setText("⬅");
        jButtonGoBack.setToolTipText("Torna enrere");
        jButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoBackActionPerformed(evt);
            }
        });

        jTableQueryResult.setAutoCreateRowSorter(true);
        jTableQueryResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableQueryResult.setFocusable(false);
        jTableQueryResult.setRowSelectionAllowed(false);
        jTableQueryResult.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTableQueryResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableQueryResult.setShowGrid(false);
        jScrollPane3.setViewportView(jTableQueryResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGoBack)
                        .addGap(0, 405, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoBackActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonGoBackActionPerformed
    private ResultSet executeQuery(Connection con, String query) {

        try {

            stmt = con.createStatement();

            rs = stmt.executeQuery(query);

            return rs;

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

            return null;
        }
    }

    private void getDadesFactura(int num_factura) {
        try {
            String query = "SELECT DISTINCT producte.nom_comercial, producte.preu_unitari, factura_producte.quantitat, (producte.preu_unitari * factura_producte.quantitat) "
                    + "AS Preu_Total from producte "
                    + "INNER JOIN factura_producte on '"+ num_factura +"' = factura_producte.num_factura and factura_producte.codi_producte = producte.codi;";
            ResultSet result = executeQuery(con, query);
            System.out.println(query);
            if (result == null) {
                JOptionPane.showMessageDialog(this, "Aquesta factura no te detalls que mostrar", "Error", JOptionPane.ERROR_MESSAGE);
                dispose();
            } else {
                ResultSetMetaData resultMetaData = result.getMetaData();
                //System.out.println("List of column names in the current table: ");

                int nCols = resultMetaData.getColumnCount();
                String cols[] = new String[nCols];

                for (int i = 1; i <= nCols; i++) {
                    tableModel.addColumn(resultMetaData.getColumnName(i));
                }

                while (result.next()) {

                    Object[] rowData = new Object[nCols];

                    for (int i = 0; i < nCols; i++) {
                        rowData[i] = rs.getObject(i + 1);
                    }
                    tableModel.addRow(rowData);

                }

                jTableQueryResult.setModel(tableModel);
                jTableQueryResult.setColumnSelectionAllowed(false);
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableQueryResult;
    // End of variables declaration//GEN-END:variables
}
