
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Aleix
 */
public class FacturaInsert extends javax.swing.JFrame {

    /**
     * Creates new form ClientInsert
     */
    Connection con;
    public static Statement stmt = null;
    public static ResultSet rs = null;
    String DNI;
    JComponent items[][] = new JComponent[5][3];

    public FacturaInsert(Connection c, String DNI) {
        con = c;
        initComponents();
        this.setLocationRelativeTo(null);
        this.DNI = DNI;

        items[0][0] = jComboBoxProductes;
        items[0][1] = jSpinnerQuantitatProducte;
        items[0][2] = jLabelPreuProducte;

        items[1][0] = jComboBoxProductes1;
        items[1][1] = jSpinnerQuantitatProducte1;
        items[1][2] = jLabelPreuProducte1;

        items[2][0] = jComboBoxProductes2;
        items[2][1] = jSpinnerQuantitatProducte2;
        items[2][2] = jLabelPreuProducte2;

        items[3][0] = jComboBoxProductes3;
        items[3][1] = jSpinnerQuantitatProducte3;
        items[3][2] = jLabelPreuProducte3;

        items[4][0] = jComboBoxProductes4;
        items[4][1] = jSpinnerQuantitatProducte4;
        items[4][2] = jLabelPreuProducte4;

        getProducts();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGoBack = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcio = new javax.swing.JTextArea();
        jLabelPreuTotal = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jSpinnerQuantitatProducte = new javax.swing.JSpinner();
        jLabelPreuProducte = new javax.swing.JLabel();
        jLabelQuantitat = new javax.swing.JLabel();
        jComboBoxProductes = new javax.swing.JComboBox<>();
        jLabelProductes = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jSpinnerQuantitatProducte1 = new javax.swing.JSpinner();
        jLabelPreuProducte1 = new javax.swing.JLabel();
        jLabelQuantitat1 = new javax.swing.JLabel();
        jComboBoxProductes1 = new javax.swing.JComboBox<>();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jSpinnerQuantitatProducte2 = new javax.swing.JSpinner();
        jLabelPreuProducte2 = new javax.swing.JLabel();
        jLabelQuantitat2 = new javax.swing.JLabel();
        jComboBoxProductes2 = new javax.swing.JComboBox<>();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jSpinnerQuantitatProducte3 = new javax.swing.JSpinner();
        jLabelPreuProducte3 = new javax.swing.JLabel();
        jLabelQuantitat3 = new javax.swing.JLabel();
        jComboBoxProductes3 = new javax.swing.JComboBox<>();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jSpinnerQuantitatProducte4 = new javax.swing.JSpinner();
        jLabelPreuProducte4 = new javax.swing.JLabel();
        jLabelQuantitat4 = new javax.swing.JLabel();
        jComboBoxProductes4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nova Factura");

        jButtonGoBack.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonGoBack.setText("⬅");
        jButtonGoBack.setToolTipText("Torna enrere");
        jButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoBackActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancel.setText("Cancela");
        jButtonCancel.setToolTipText("");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonCreate.setBackground(new java.awt.Color(102, 255, 102));
        jButtonCreate.setText("Crear");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripcio:");

        jTextAreaDescripcio.setColumns(20);
        jTextAreaDescripcio.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcio);

        jSpinnerQuantitatProducte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQuantitatProducteStateChanged(evt);
            }
        });

        jLabelPreuProducte.setText("preu");

        jLabelQuantitat.setText("Quantitat:");

        jComboBoxProductes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un producte" }));
        jComboBoxProductes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductesActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jSpinnerQuantitatProducte, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelPreuProducte, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelQuantitat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBoxProductes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxProductes, 0, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuantitat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerQuantitatProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelPreuProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuantitat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerQuantitatProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProductes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPreuProducte))
                .addContainerGap())
        );

        jLabelProductes.setText("Productes:");

        jSpinnerQuantitatProducte1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQuantitatProducte1StateChanged(evt);
            }
        });

        jLabelPreuProducte1.setText("preu");

        jLabelQuantitat1.setText("Quantitat:");

        jComboBoxProductes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un producte" }));
        jComboBoxProductes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductes1ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jSpinnerQuantitatProducte1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabelPreuProducte1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabelQuantitat1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jComboBoxProductes1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxProductes1, 0, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuantitat1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerQuantitatProducte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelPreuProducte1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuantitat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerQuantitatProducte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProductes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPreuProducte1))
                .addContainerGap())
        );

        jSpinnerQuantitatProducte2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQuantitatProducte2StateChanged(evt);
            }
        });

        jLabelPreuProducte2.setText("preu");

        jLabelQuantitat2.setText("Quantitat:");

        jComboBoxProductes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un producte" }));
        jComboBoxProductes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductes2ActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jSpinnerQuantitatProducte2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabelPreuProducte2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabelQuantitat2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jComboBoxProductes2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxProductes2, 0, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuantitat2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerQuantitatProducte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelPreuProducte2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuantitat2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerQuantitatProducte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProductes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPreuProducte2))
                .addContainerGap())
        );

        jSpinnerQuantitatProducte3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQuantitatProducte3StateChanged(evt);
            }
        });

        jLabelPreuProducte3.setText("preu");

        jLabelQuantitat3.setText("Quantitat:");

        jComboBoxProductes3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un producte" }));
        jComboBoxProductes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductes3ActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jSpinnerQuantitatProducte3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabelPreuProducte3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabelQuantitat3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jComboBoxProductes3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxProductes3, 0, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuantitat3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerQuantitatProducte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelPreuProducte3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuantitat3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerQuantitatProducte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProductes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPreuProducte3))
                .addContainerGap())
        );

        jSpinnerQuantitatProducte4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQuantitatProducte4StateChanged(evt);
            }
        });

        jLabelPreuProducte4.setText("preu");

        jLabelQuantitat4.setText("Quantitat:");

        jComboBoxProductes4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un producte" }));
        jComboBoxProductes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductes4ActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(jSpinnerQuantitatProducte4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabelPreuProducte4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabelQuantitat4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jComboBoxProductes4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxProductes4, 0, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuantitat4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerQuantitatProducte4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelPreuProducte4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuantitat4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerQuantitatProducte4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProductes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPreuProducte4))
                .addContainerGap())
        );

        jLabel2.setText("Total:");

        jLabel3.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButtonGoBack)
                            .addComponent(jLabelProductes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCancel)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCreate))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPreuTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabelProductes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2))
                    .addComponent(jLabelPreuTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoBackActionPerformed
        FacturesClient obj = new FacturesClient(con, DNI);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGoBackActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        FacturesClient obj = new FacturesClient(con, DNI);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        int preu_unitari = 0, num_factura = 0, codi_producte = 0;
        try {
            try {
                stmt = con.createStatement();
                String query = "INSERT INTO factura (descripcio, total, dni_client, nss_treballador) "
                        + "VALUES ('" + jTextAreaDescripcio.getText() + "', '" + jLabelPreuTotal.getText() + "', '" + DNI + "', '1237897645');";
                stmt.executeUpdate(query);
                String query1 = "SELECT num_factura FROM factura ORDER BY num_factura DESC LIMIT 1";
                rs = stmt.executeQuery(query1);
                while (rs.next()) {
                    num_factura = rs.getInt("num_factura");

                }

            } catch (Exception e) {
                String txt = "Error al inserir factura: " + e;
                JOptionPane.showMessageDialog(this, txt, "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println(txt);
            }
            try {
                //System.out.println(query);
                System.out.println("ID ULTIM: " + num_factura);
                for (int i = 0; i < items.length; i++) {
                    stmt = con.createStatement();
                    String nom = String.valueOf(((JComboBox<String>) items[i][0]).getSelectedItem());
                    if (!nom.equals("Selecciona un producte")) {
                    String query1 = "SELECT * FROM producte WHERE nom_comercial = '" + nom + "'";

                    rs = stmt.executeQuery(query1);
                    
                    while (rs.next()) {
                        preu_unitari = rs.getInt("preu_unitari");
                        codi_producte = rs.getInt("codi");
                    }

                    String query2 = "INSERT INTO factura_producte (num_factura, codi_producte, quantitat, preu_unitari) "
                            + "VALUES ('" + num_factura + "', '" + codi_producte + "', '" + (((JSpinner) items[i][1]).getValue()) + "', '" + preu_unitari + "');";

                    stmt.executeUpdate(query2);
                    }
                }

                JOptionPane.showMessageDialog(this, "Factura creada correctament", "Status", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                FacturesClient obj = new FacturesClient(con, DNI);
                obj.setVisible(true);
            } catch (Exception e) {
                String txt = "Error al inserir productes a factura: " + e;
                JOptionPane.showMessageDialog(this, txt, "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println(txt);
            }
        } catch (Exception e) {
            String txt = "Error al crear factura: " + e;
            JOptionPane.showMessageDialog(this, txt, "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(txt);
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jComboBoxProductesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductesActionPerformed
        getProductePreu();
    }//GEN-LAST:event_jComboBoxProductesActionPerformed

    private void jSpinnerQuantitatProducteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQuantitatProducteStateChanged
        getProductePreu();
    }//GEN-LAST:event_jSpinnerQuantitatProducteStateChanged

    private void jSpinnerQuantitatProducte1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQuantitatProducte1StateChanged
        getProductePreu();
    }//GEN-LAST:event_jSpinnerQuantitatProducte1StateChanged

    private void jComboBoxProductes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductes1ActionPerformed
        getProductePreu();
    }//GEN-LAST:event_jComboBoxProductes1ActionPerformed

    private void jSpinnerQuantitatProducte2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQuantitatProducte2StateChanged
        getProductePreu();
    }//GEN-LAST:event_jSpinnerQuantitatProducte2StateChanged

    private void jComboBoxProductes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductes2ActionPerformed
        getProductePreu();
    }//GEN-LAST:event_jComboBoxProductes2ActionPerformed

    private void jSpinnerQuantitatProducte3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQuantitatProducte3StateChanged
        getProductePreu();
    }//GEN-LAST:event_jSpinnerQuantitatProducte3StateChanged

    private void jComboBoxProductes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductes3ActionPerformed
        getProductePreu();
    }//GEN-LAST:event_jComboBoxProductes3ActionPerformed

    private void jSpinnerQuantitatProducte4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQuantitatProducte4StateChanged
        getProductePreu();
     }//GEN-LAST:event_jSpinnerQuantitatProducte4StateChanged

    private void jComboBoxProductes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductes4ActionPerformed
        getProductePreu();
    }//GEN-LAST:event_jComboBoxProductes4ActionPerformed
    private void getProductePreu() {
        int preuTotal = 0;
        for (int i = 0; i < items.length; i++) {
            String nom = String.valueOf(((JComboBox<String>) items[i][0]).getSelectedItem());
            try {
                stmt = con.createStatement();
                String query = "SELECT preu_unitari FROM producte WHERE nom_comercial = '" + nom + "'";

                rs = stmt.executeQuery(query);

                int preu = (int) ((JSpinner) items[i][1]).getValue();
                while (rs.next()) {
                    preu = (int) ((JSpinner) items[i][1]).getValue() * rs.getInt("preu_unitari");
                }
                //System.out.println(preu);
                if (!nom.equals("Selecciona un producte")) {
                    ((JLabel) items[i][2]).setText(Integer.toString(preu));
                    preuTotal += Integer.parseInt(((JLabel) items[i][2]).getText());
                } else {
                    ((JLabel) items[i][2]).setText("0");
                }
            } catch (Exception e) {
                String txt = "Error al consultar producte: " + e;
                System.out.println(txt);
            }
        }
        jLabelPreuTotal.setText(Integer.toString(preuTotal));
    }

    private void getProducts() {
        for (int i = 0; i < items.length; i++) {
            ((JSpinner) items[i][1]).setValue(1);
            ((JLabel) items[i][2]).setText("0");
            try {
                String query = "SELECT * FROM producte";
                stmt = con.createStatement();
                rs = stmt.executeQuery(query);
                while (rs.next()) {
                    ((JComboBox<String>) items[i][0]).addItem(rs.getString("nom_comercial"));
                }
            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JComboBox<String> jComboBoxProductes;
    private javax.swing.JComboBox<String> jComboBoxProductes1;
    private javax.swing.JComboBox<String> jComboBoxProductes2;
    private javax.swing.JComboBox<String> jComboBoxProductes3;
    private javax.swing.JComboBox<String> jComboBoxProductes4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPreuProducte;
    private javax.swing.JLabel jLabelPreuProducte1;
    private javax.swing.JLabel jLabelPreuProducte2;
    private javax.swing.JLabel jLabelPreuProducte3;
    private javax.swing.JLabel jLabelPreuProducte4;
    private javax.swing.JLabel jLabelPreuTotal;
    private javax.swing.JLabel jLabelProductes;
    private javax.swing.JLabel jLabelQuantitat;
    private javax.swing.JLabel jLabelQuantitat1;
    private javax.swing.JLabel jLabelQuantitat2;
    private javax.swing.JLabel jLabelQuantitat3;
    private javax.swing.JLabel jLabelQuantitat4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerQuantitatProducte;
    private javax.swing.JSpinner jSpinnerQuantitatProducte1;
    private javax.swing.JSpinner jSpinnerQuantitatProducte2;
    private javax.swing.JSpinner jSpinnerQuantitatProducte3;
    private javax.swing.JSpinner jSpinnerQuantitatProducte4;
    private javax.swing.JTextArea jTextAreaDescripcio;
    // End of variables declaration//GEN-END:variables
}
